steps:
  # Create Docker Buildx builder
  - name: 'docker'
    args: [ 'buildx', 'create', '--name', 'mybuilder', '--use' ]

  # Build and push for multiple architectures
  - name: 'docker'
    args:
      [
        'buildx', 'build',
        '--platform', 'linux/arm64,linux/amd64',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/foo:latest',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/foo:${SHORT_SHA}',
        '--cache-from', 'type=registry,ref=us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/foo:latest:buildcache',
        '--cache-to', 'type=us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/foo:latest:buildcache,mode=max',
        '--push',
        '.',
      ]

timeout: "3600s"

options:
  machineType: "N1_HIGHCPU_8"